sudo: false
language: node_js
node_js:
  - '12'
branches:
  only:
    - master
    - dev
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
  - yarn run coveralls
  