version: '3'
services:
  node:
    container_name: server
    image: node:10.15.1-alpine
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    command: yarn dev
  mongo:
    container_name: mongodb
    image: "mvertes/alpine-mongo"
    ports:
      - "27017:27017"
